database:
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=root; Password=toor;" # See https://www.connectionstrings.com/mysql/ for more information on making ConnectionStrings